language: python
python:
  - "3.3.2"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - npm install --quiet -g karma
  - npm install --quiet -g grunt-cli
  - npm install --quiet -g protractor

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd site
  - npm install
  - ./scripts/web-server.js > /dev/null &
  - sleep 2  # give server time to start

script:
  - grunt test
  - cd ../
  - DJANGO_SETTINGS_MODULE=gymjournals.settings py.test
